name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build-test:
    uses: liquibase/build-logic/.github/workflows/pro-extension-test.yml@v0.2.4
    secrets: inherit

  integration-test:
    needs: build-test
    name: Java ${{ matrix.java }} | Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11, 17, 18 ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Tests With Maven
        run: mvn --quiet --show-version --batch-mode verify
        env:
          LIQUIBASE_GIT_USERNAME: liquibot
          LIQUIBASE_GIT_PASSWORD: ${{ secrets.BOT_TOKEN }}
